# Site settings
title: Insha Kanue | Front End Developer
keywords: Insha, Insha Kanue, Front-End, Developer, Web Developer, Computer Science Engineer, Kashmir, Srinagar, Anantnag, tech blogging, design, UI, user interface, UX, user experience, user experience design  
description: Portfolio website of Front-End Developer Insha Kanue
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Insha Kanue
user_description: Front-End Developer
user_title: Front-End Developer
#email:
linkedin_username: inshakanue
twitter_username: InshaKanue
github_username: inshakanue
dribbble_username: InshaKanue
facebook_username: InshaKanue


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
